### ISSUE TITLE
How to install the log view on Windows?

### ISSUE THREAD

**Issue by idk-278** [mlopatkin/andlogview#242]
Hey, I am quite new on Github and I can't figure out how to download the log file and use it on my PC.

I tried downloading the ZIP file from the green-colored "CODE" button but cannot figure out where will I find the log viewer.

Help will be appreciated, thank you in advance.

**Comment by mlopatkin** [comment]
Hi, looks like you're downloading the code archive. It isn't very useful unless you're going to build the tool from the sources.
Binary releases can be found under the "Releases" link on the main page:
![releases](https://user-images.githubusercontent.com/7620037/181209310-1df88bc4-9027-4baf-802c-14a2dd5f91ee.png)

On the individual release page you can find the binary archive under "Assets":
![single release](https://user-images.githubusercontent.com/7620037/181208638-9be8bf16-9d76-4368-bb93-07c298ac4859.png)

Then you can unpack the archive wherever you want and use `bin/andlogview.bat` to run the tool.

Note that you have to use Java 8 (or higher) installed separately and either have the path to the folder containing `java` executable in `PATH` environment variable or `JAVA_HOME` environment variable set to the folder containing the Java installation. If you want to capture the live logs from the connected device, then you need the `adb` tool as well, you can get it as part of the Android SDK with Android Studio or [standalone](https://developer.android.com/studio/releases/platform-tools#downloads). On Windows it is probably necessary to have device drivers for the phone as well.
